export const GET_CARD_LIST = {
  REQUEST: 'GET_CARD_LIST_REQUEST',
  SUCCESS: 'GET_CARD_LIST_SUCCESS',
  FAILURE: 'GET_CARD_LIST_FAILURE',
};

export const GET_CARD_TOTAL_COUNT = {
  REQUEST: 'GET_CARD_TOTAL_COUNT_REQUEST',
  SUCCESS: 'GET_CARD_TOTAL_COUNT_SUCCESS',
  FAILURE: 'GET_CARD_TOTAL_COUNT_FAILURE',
};

export const GET_CARD_DETAIL = {
  REQUEST: 'GET_CARD_DETAIL_REQUEST',
  SUCCESS: 'GET_CARD_DETAIL_SUCCESS',
  FAILURE: 'GET_CARD_DETAIL_FAILURE',
};

export const UPDATE_CARD = {
  REQUEST: 'UPDATE_CARD_REQUEST',
  SUCCESS: 'UPDATE_CARD_SUCCESS',
  FAILURE: 'UPDATE_CARD_FAILURE',
};

export const CREATE_CARD = {
  REQUEST: 'CREATE_CARD_REQUEST',
  SUCCESS: 'CREATE_CARD_SUCCESS',
  FAILURE: 'CREATE_CARD_FAILURE',
};

export const DELETE_CARD = {
  REQUEST: 'DELETE_CARD_REQUEST',
  SUCCESS: 'DELETE_CARD_SUCCESS',
  FAILURE: 'DELETE_CARD_FAILURE',
};

export const CARD_STATUS = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  DELETED: 'DELETED',
};

export const APPROVE_CARD = {
  REQUEST: 'APPROVE_CARD_REQUEST',
  SUCCESS: 'APPROVE_CARD_SUCCESS',
  FAILURE: 'APPROVE_CARD_FAILURE',
};

export const REJECT_CARD = {
  REQUEST: 'REJECT_CARD_REQUEST',
  SUCCESS: 'REJECT_CARD_SUCCESS',
  FAILURE: 'REJECT_CARD_FAILURE',
};

export const UPDATE_CARD_LIST = {
  REQUEST: 'UPDATE_CARD_LIST_REQUEST',
  SUCCESS: 'UPDATE_CARD_LIST_SUCCESS',
  FAILURE: 'UPDATE_CARD_LIST_FAILURE',
};

