export const GET_CUISINE_TYPE_TOTAL_COUNT = {
  REQUEST: 'GET_CUISINE_TYPE_TOTAL_COUNT_REQUEST',
  SUCCESS: 'GET_CUISINE_TYPE_TOTAL_COUNT_SUCCESS',
  FAILURE: 'GET_CUISINE_TYPE_TOTAL_COUNT_FAILURE',
};

export const GET_CUISINE_TYPE_LIST = {
  REQUEST: 'GET_CUISINE_TYPE_LIST_REQUEST',
  SUCCESS: 'GET_CUISINE_TYPE_LIST_SUCCESS',
  FAILURE: 'GET_CUISINE_TYPE_LIST_FAILURE',
};

export const UPDATE_CUISINE_TYPE = {
  REQUEST: 'UPDATE_CUISINE_TYPE_REQUEST',
  SUCCESS: 'UPDATE_CUISINE_TYPE_SUCCESS',
  FAILURE: 'UPDATE_CUISINE_TYPE_FAILURE',
};

export const CREATE_CUISINE_TYPE = {
  REQUEST: 'CREATE_CUISINE_TYPE_REQUEST',
  SUCCESS: 'CREATE_CUISINE_TYPE_SUCCESS',
  FAILURE: 'CREATE_CUISINE_TYPE_FAILURE',
};

export const DELETE_CUISINE_TYPE = {
  REQUEST: 'DELETE_CUISINE_TYPE_REQUEST',
  SUCCESS: 'DELETE_CUISINE_TYPE_SUCCESS',
  FAILURE: 'DELETE_CUISINE_TYPE_FAILURE',
};
