export const GET_REPORT_TOTAL_COUNT = {
  REQUEST: 'GET_REPORT_TOTAL_COUNT_REQUEST',
  SUCCESS: 'GET_REPORT_TOTAL_COUNT_SUCCESS',
  FAILURE: 'GET_REPORT_TOTAL_COUNT_FAILURE',
};

export const GET_REPORT_LIST = {
  REQUEST: 'GET_REPORT_LIST_REQUEST',
  SUCCESS: 'GET_REPORT_LIST_SUCCESS',
  FAILURE: 'GET_REPORT_LIST_FAILURE',
};

export const DELETE_REPORT = {
  REQUEST: 'DELETE_REPORT_REQUEST',
  SUCCESS: 'DELETE_REPORT_SUCCESS',
  FAILURE: 'DELETE_REPORT_FAILURE',
};

export const REPORT_STATUS = {
  PENDING: 'PENDING',
  DELETED: 'DELETED',
};
