export const GET_RESTAURANT_TOTAL_COUNT = {
  REQUEST: 'GET_RESTAURANT_TOTAL_COUNT_REQUEST',
  SUCCESS: 'GET_RESTAURANT_TOTAL_COUNT_SUCCESS',
  FAILURE: 'GET_RESTAURANT_TOTAL_COUNT_FAILURE',
};

export const GET_RESTAURANT_LIST = {
  REQUEST: 'GET_RESTAURANT_LIST_REQUEST',
  SUCCESS: 'GET_RESTAURANT_LIST_SUCCESS',
  FAILURE: 'GET_RESTAURANT_LIST_FAILURE',
};

export const GET_RESTAURANT_DETAIL = {
  REQUEST: 'GET_RESTAURANT_DETAIL_REQUEST',
  SUCCESS: 'GET_RESTAURANT_DETAIL_SUCCESS',
  FAILURE: 'GET_RESTAURANT_DETAIL_FAILURE',
};

export const UPDATE_RESTAURANT = {
  REQUEST: 'UPDATE_RESTAURANT_REQUEST',
  SUCCESS: 'UPDATE_RESTAURANT_SUCCESS',
  FAILURE: 'UPDATE_RESTAURANT_FAILURE',
};

export const CREATE_RESTAURANT = {
  REQUEST: 'CREATE_RESTAURANT_REQUEST',
  SUCCESS: 'CREATE_RESTAURANT_SUCCESS',
  FAILURE: 'CREATE_RESTAURANT_FAILURE',
};

export const DELETE_RESTAURANT = {
  REQUEST: 'DELETE_RESTAURANT_REQUEST',
  SUCCESS: 'DELETE_RESTAURANT_SUCCESS',
  FAILURE: 'DELETE_RESTAURANT_FAILURE',
};

export const UPDATE_RESTAURANT_LIST = {
  REQUEST: 'UPDATE_RESTAURANT_LIST_REQUEST',
  SUCCESS: 'UPDATE_RESTAURANT_LIST_SUCCESS',
  FAILURE: 'UPDATE_RESTAURANT_LIST_FAILURE',
};
